import esbuild from "esbuild";
import builtins from "builtin-modules";
import process from "process";

const production = process.argv[2] === "production";
const context = await esbuild.context({
  entryPoints: ["publish/main.ts"],
  bundle: true,
  external: ["obsidian", "electron", ...builtins],
  format: "cjs",
  target: "es2018",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  logLevel: "info",
  outfile: "publish/main.js",
  banner: { js: "/* Generated by esbuild. See main.ts for source. */" }
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
