/* Generated by esbuild. See publish/main.ts for source. */
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// publish/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => KairoQuickCapturePlugin
});
module.exports = __toCommonJS(main_exports);

// main.ts
var import_obsidian = require("obsidian");

// src/core.ts
function formatTimestamp(date, format) {
  const pad = (value) => String(value).padStart(2, "0");
  const replacements = {
    YYYY: String(date.getFullYear()),
    MM: pad(date.getMonth() + 1),
    DD: pad(date.getDate()),
    HH: pad(date.getHours()),
    mm: pad(date.getMinutes()),
    ss: pad(date.getSeconds())
  };
  return format.replace(/YYYY|MM|DD|HH|mm|ss/g, (token) => replacements[token]);
}
function renderTemplate(template, context) {
  return template.replace(/\{\{\s*(time|source|text|id)\s*\}\}/gi, (_, key) => {
    const normalized = key.toLowerCase();
    return context[normalized];
  });
}
function normalizeVaultPath(path) {
  return path.trim().replace(/\\/g, "/").replace(/^\/+|\/+$/g, "");
}
function joinVaultPath(folder, file) {
  const left = normalizeVaultPath(folder);
  const right = normalizeVaultPath(file);
  return [left, right].filter(Boolean).join("/");
}
function dailyNotePath(folder, date, format) {
  return joinVaultPath(folder, `${formatTimestamp(date, format)}.md`);
}
function appendText(existing, entry) {
  if (!existing) return entry;
  const separator = existing.endsWith("\n") ? "" : "\n";
  return `${existing}${separator}${entry}`;
}
function diagnosticSummary(destination, error, queueId) {
  const message = error instanceof Error ? error.message : String(error);
  return `Kairo could not deliver capture ${queueId}. Destination: ${destination}. Reason: ${message}`;
}

// main.ts
var DEFAULT_TEMPLATE = "- {{time}} \u2014 {{text}}\n";
var DEFAULT_SETTINGS = {
  shortcut: "Ctrl+Shift+Space",
  vaultFolder: "",
  destinationMode: "inbox",
  inboxPath: "Inbox.md",
  dailyFolder: "Daily",
  dailyFormat: "YYYY-MM-DD",
  template: DEFAULT_TEMPLATE,
  timestampFormat: "YYYY-MM-DD HH:mm",
  createMissing: false,
  closeAfterSaving: true,
  launchAtLogin: false,
  setupCompleted: false
};
var DestinationChangedError = class extends Error {
  constructor() {
    super("The destination changed while Kairo was preparing the append. Nothing was overwritten.");
    this.name = "DestinationChangedError";
  }
};
var KairoQuickCapturePlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.queue = [];
  }
  async onload() {
    var _a;
    const data = await this.loadData();
    this.settings = { ...DEFAULT_SETTINGS, ...(_a = data == null ? void 0 : data.settings) != null ? _a : {} };
    this.queue = Array.isArray(data == null ? void 0 : data.queue) ? data.queue : [];
    this.addCommand({
      id: "open-capture",
      name: "Open quick capture",
      hotkeys: [{ modifiers: ["Mod", "Shift"], key: "K" }],
      callback: () => this.openCapture()
    });
    this.addCommand({
      id: "flush-queue",
      name: "Flush queued captures",
      callback: () => void this.flushQueue(true)
    });
    this.addCommand({
      id: "show-queue",
      name: "Show queued captures",
      callback: () => new QueueModal(this.app, this).open()
    });
    this.addCommand({
      id: "run-setup",
      name: "Run Kairo setup",
      callback: () => new SetupModal(this.app, this).open()
    });
    this.addSettingTab(new KairoSettingTab(this.app, this));
    this.registerInterval(window.setInterval(() => void this.flushQueue(false), 6e4));
    this.app.workspace.onLayoutReady(() => {
      this.registerGlobalShortcut();
      void this.flushQueue(false);
      if (!this.settings.setupCompleted) window.setTimeout(() => new SetupModal(this.app, this).open(), 500);
    });
  }
  onunload() {
    this.unregisterGlobalShortcut();
  }
  async persist() {
    await this.saveData({ settings: this.settings, queue: this.queue });
  }
  openCapture() {
    new CaptureModal(this.app, this).open();
  }
  destinationFor(date = /* @__PURE__ */ new Date()) {
    const relative = this.settings.destinationMode === "daily" ? dailyNotePath(this.settings.dailyFolder, date, this.settings.dailyFormat) : normalizeVaultPath(this.settings.inboxPath);
    return joinVaultPath(this.settings.vaultFolder, relative);
  }
  async capture(text) {
    const trimmed = text.trimEnd();
    if (!trimmed.trim()) throw new Error("Capture is empty.");
    const id = this.makeId();
    const now = /* @__PURE__ */ new Date();
    const destination = this.destinationFor(now);
    const entry = renderTemplate(this.settings.template, {
      time: formatTimestamp(now, this.settings.timestampFormat),
      source: "Obsidian",
      text: trimmed,
      id
    });
    try {
      await this.appendSafely(destination, entry, id);
      return { state: "saved", id };
    } catch (error) {
      const queued = { id, createdAt: now.getTime(), destination, entry, attempts: 1, lastError: diagnosticSummary(destination, error, id) };
      this.queue.push(queued);
      try {
        await this.persist();
        return { state: "queued", id, diagnostic: queued.lastError };
      } catch (persistError) {
        queued.lastError = diagnosticSummary(destination, persistError, id);
        return { state: "failed", id, diagnostic: queued.lastError };
      }
    }
  }
  async flushQueue(showNotice) {
    if (!this.queue.length) {
      if (showNotice) new import_obsidian.Notice("Kairo queue is empty.");
      return;
    }
    const pending = [...this.queue].sort((a, b) => a.createdAt - b.createdAt);
    const remaining = [];
    let delivered = 0;
    for (const item of pending) {
      try {
        await this.appendSafely(item.destination, item.entry, item.id);
        delivered++;
      } catch (error) {
        remaining.push({ ...item, attempts: item.attempts + 1, lastError: diagnosticSummary(item.destination, error, item.id) });
      }
    }
    this.queue = remaining;
    await this.persist();
    if (showNotice) new import_obsidian.Notice(remaining.length ? `Delivered ${delivered}; ${remaining.length} still queued.` : `Delivered ${delivered} queued capture${delivered === 1 ? "" : "s"}.`);
  }
  async validateDestination() {
    const path = this.destinationFor();
    if (!path) return { ok: false, path, reason: "Choose an inbox file or daily-note folder first." };
    const folder = this.settings.vaultFolder ? this.app.vault.getAbstractFileByPath(normalizeVaultPath(this.settings.vaultFolder)) : null;
    if (this.settings.vaultFolder && !(folder instanceof import_obsidian.TFolder)) return { ok: false, path, reason: "Vault folder does not exist in the current vault." };
    const file = this.app.vault.getAbstractFileByPath(path);
    if (file && !(file instanceof import_obsidian.TFile)) return { ok: false, path, reason: "The destination path is a folder, not a Markdown file." };
    if (!file && !this.settings.createMissing) return { ok: false, path, reason: "Destination is missing. Enable 'Create missing destinations' to allow creation." };
    return { ok: true, path };
  }
  async appendSafely(path, entry, marker) {
    const normalized = (0, import_obsidian.normalizePath)(path);
    if (!normalized || normalized.includes("../") || normalized === "..") throw new Error("Destination must stay inside the current vault.");
    const existing = this.app.vault.getAbstractFileByPath(normalized);
    if (existing && !(existing instanceof import_obsidian.TFile)) throw new Error("Destination path is a folder.");
    if (!existing) {
      if (!this.settings.createMissing) throw new Error("Destination file does not exist and creation is disabled.");
      await this.ensureParentFolders(normalized);
      const markedEntry2 = `${entry}${entry.endsWith("\n") ? "" : "\n"}<!-- kairo:${marker} -->
`;
      await this.app.vault.create(normalized, markedEntry2);
      return;
    }
    const file = existing;
    const before = file.stat.mtime;
    const contents = await this.app.vault.read(file);
    if (contents.includes(`<!-- kairo:${marker} -->`)) return;
    const current = file.stat.mtime;
    if (current !== before) throw new DestinationChangedError();
    const markedEntry = `${entry}${entry.endsWith("\n") ? "" : "\n"}<!-- kairo:${marker} -->
`;
    await this.app.vault.modify(file, appendText(contents, markedEntry));
  }
  async ensureParentFolders(path) {
    const parts = path.split("/");
    parts.pop();
    let current = "";
    for (const part of parts) {
      current = current ? `${current}/${part}` : part;
      const existing = this.app.vault.getAbstractFileByPath(current);
      if (existing && !(existing instanceof import_obsidian.TFolder)) throw new Error(`Cannot create destination folder: ${current} is a file.`);
      if (!existing) await this.app.vault.createFolder(current);
    }
  }
  copyDiagnostic(summary) {
    var _a;
    const write = (_a = navigator.clipboard) == null ? void 0 : _a.writeText(summary);
    if (write) void write.then(() => new import_obsidian.Notice("Diagnostic copied. Captured text was not included."));
    else new import_obsidian.Notice("Clipboard access is unavailable. The diagnostic is visible in the queue.");
  }
  makeId() {
    const bytes = new Uint8Array(8);
    crypto.getRandomValues(bytes);
    return `kairo-${Date.now().toString(36)}-${Array.from(bytes, (value) => value.toString(16).padStart(2, "0")).join("")}`;
  }
  registerGlobalShortcut() {
    this.unregisterGlobalShortcut();
    const electron = this.electron();
    if (!(electron == null ? void 0 : electron.globalShortcut)) return;
    try {
      if (electron.globalShortcut.register(this.settings.shortcut, () => this.openCapture())) this.globalShortcut = this.settings.shortcut;
    } catch (e) {
    }
  }
  unregisterGlobalShortcut() {
    var _a, _b;
    if (!this.globalShortcut) return;
    try {
      (_b = (_a = this.electron()) == null ? void 0 : _a.globalShortcut) == null ? void 0 : _b.unregister(this.globalShortcut);
    } catch (e) {
    }
    this.globalShortcut = void 0;
  }
  applyLaunchAtLogin() {
    var _a, _b, _c;
    try {
      (_c = (_b = (_a = this.electron()) == null ? void 0 : _a.app) == null ? void 0 : _b.setLoginItemSettings) == null ? void 0 : _c.call(_b, { openAtLogin: this.settings.launchAtLogin });
    } catch (e) {
    }
  }
  refreshShortcut() {
    this.registerGlobalShortcut();
  }
  electron() {
    const requireFn = window.require;
    if (!requireFn) return void 0;
    try {
      return requireFn("electron");
    } catch (e) {
      return void 0;
    }
  }
};
var CaptureModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    this.modalEl.addClass("kairo-capture-modal");
    this.titleEl.setText("Quick capture");
    this.contentEl.empty();
    this.contentEl.createEl("p", { text: "Capture locally; Kairo will deliver it to your configured destination." });
    this.textarea = this.contentEl.createEl("textarea", { attr: { ariaLabel: "Capture text", rows: "7", placeholder: "What do you want to remember?" } });
    this.status = this.contentEl.createDiv({ cls: "kairo-status", attr: { role: "status", "aria-live": "polite" } });
    this.status.setText("Ready");
    const actions = this.contentEl.createDiv({ cls: "kairo-actions" });
    const save = actions.createEl("button", { text: "Save" });
    const saveClose = actions.createEl("button", { text: "Save and close", cls: "mod-cta" });
    const cancel = actions.createEl("button", { text: "Cancel" });
    save.addEventListener("click", () => void this.submit(false));
    saveClose.addEventListener("click", () => void this.submit(true));
    cancel.addEventListener("click", () => this.close());
    this.textarea.addEventListener("keydown", (event) => {
      if (event.key === "Escape") {
        event.preventDefault();
        this.close();
      }
      if ((event.ctrlKey || event.metaKey) && event.key === "Enter") {
        event.preventDefault();
        void this.submit(this.plugin.settings.closeAfterSaving);
      }
    });
    window.setTimeout(() => this.textarea.focus(), 20);
  }
  async submit(closeAfter) {
    if (!this.textarea.value.trim()) {
      this.status.setText("Enter some text first.");
      return;
    }
    this.status.setText("Saving\u2026");
    try {
      const result = await this.plugin.capture(this.textarea.value);
      if (result.state === "saved") {
        this.status.setText("Saved");
        new import_obsidian.Notice("Capture saved.");
        if (closeAfter || this.plugin.settings.closeAfterSaving) this.close();
      } else if (result.state === "queued") {
        this.diagnostic = result.diagnostic;
        this.status.setText("Queued \u2014 destination unavailable. Your text is safe locally.");
        this.addDiagnosticAction();
        if (closeAfter) this.close();
      } else {
        this.diagnostic = result.diagnostic;
        this.status.setText("Failed \u2014 the capture could not be persisted. Keep this window open and retry.");
        this.addDiagnosticAction();
      }
    } catch (error) {
      this.status.setText(error instanceof Error ? error.message : "Could not save capture.");
    }
  }
  addDiagnosticAction() {
    if (!this.diagnostic) return;
    const copy = this.contentEl.createEl("button", { text: "Copy diagnostic" });
    copy.addEventListener("click", () => {
      var _a;
      return this.plugin.copyDiagnostic((_a = this.diagnostic) != null ? _a : "");
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var QueueModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    this.titleEl.setText("Queued captures");
    this.contentEl.empty();
    if (!this.plugin.queue.length) {
      this.contentEl.createEl("p", { text: "Nothing is waiting for delivery." });
      return;
    }
    this.contentEl.createEl("p", { text: `${this.plugin.queue.length} capture${this.plugin.queue.length === 1 ? "" : "s"} waiting. Captured text stays in this vault's plugin data until delivery.` });
    const list = this.contentEl.createEl("ul", { cls: "kairo-queue-list" });
    for (const item of [...this.plugin.queue].sort((a, b) => a.createdAt - b.createdAt)) {
      const row = list.createEl("li");
      row.createEl("strong", { text: new Date(item.createdAt).toLocaleString() });
      row.createEl("span", { text: ` \xB7 ${item.destination} \xB7 ${item.attempts} attempt${item.attempts === 1 ? "" : "s"}` });
      if (item.lastError) {
        row.createEl("p", { text: item.lastError, cls: "kairo-queue-error" });
        const copy = row.createEl("button", { text: "Copy diagnostic" });
        copy.addEventListener("click", () => {
          var _a;
          return this.plugin.copyDiagnostic((_a = item.lastError) != null ? _a : "");
        });
      }
    }
    const retry = this.contentEl.createEl("button", { text: "Retry all", cls: "mod-cta" });
    retry.addEventListener("click", () => {
      void this.plugin.flushQueue(true).then(() => this.close());
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var SetupModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    this.titleEl.setText("Set up Kairo");
    this.contentEl.empty();
    this.contentEl.createEl("p", { text: "Kairo writes only to the current vault. Configure a destination in settings, validate it, then explicitly confirm a test capture." });
    const result = this.contentEl.createDiv({ cls: "kairo-status", attr: { role: "status", "aria-live": "polite" } });
    const validate = this.contentEl.createEl("button", { text: "Validate destination" });
    const test = this.contentEl.createEl("button", { text: "Confirm and write test capture", cls: "mod-cta" });
    const later = this.contentEl.createEl("button", { text: "Skip for now" });
    validate.addEventListener("click", () => void this.validate(result));
    test.addEventListener("click", () => void this.writeTest(result));
    later.addEventListener("click", () => this.close());
  }
  async validate(result) {
    var _a;
    const check = await this.plugin.validateDestination();
    result.setText(check.ok ? `Ready: ${check.path}` : (_a = check.reason) != null ? _a : "Destination is not ready.");
  }
  async writeTest(result) {
    var _a;
    const check = await this.plugin.validateDestination();
    if (!check.ok) {
      result.setText((_a = check.reason) != null ? _a : "Configure a destination first.");
      return;
    }
    try {
      const capture = await this.plugin.capture("Kairo setup test \u2014 safe to delete.");
      if (capture.state !== "saved") {
        result.setText(capture.state === "queued" ? "The test capture was queued; setup will finish after the destination becomes available." : "The test capture could not be persisted. Setup is not marked complete.");
        return;
      }
      this.plugin.settings.setupCompleted = true;
      await this.plugin.persist();
      result.setText("Setup complete. You can delete the test capture if you like.");
      new import_obsidian.Notice("Kairo setup complete.");
    } catch (error) {
      result.setText(error instanceof Error ? error.message : "Setup test failed.");
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var KairoSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Kairo Quick Capture" });
    containerEl.createEl("p", { text: "Local-first capture. The optional Electron shortcut is active while Obsidian is running; the Obsidian command hotkey is always available as a fallback." });
    new import_obsidian.Setting(containerEl).setName("Global shortcut").setDesc("Desktop accelerator, for example Ctrl+Shift+Space. Restart the shortcut after editing.").addText((text) => text.setValue(this.plugin.settings.shortcut).onChange(async (value) => {
      this.plugin.settings.shortcut = value.trim() || DEFAULT_SETTINGS.shortcut;
      this.plugin.refreshShortcut();
      await this.plugin.persist();
    }));
    new import_obsidian.Setting(containerEl).setName("Vault folder").setDesc("Optional folder inside the current vault. Kairo never writes outside the current vault.").addText((text) => text.setPlaceholder("Leave blank for vault root").setValue(this.plugin.settings.vaultFolder).onChange(async (value) => {
      this.plugin.settings.vaultFolder = normalizeVaultPath(value);
      await this.plugin.persist();
    }));
    new import_obsidian.Setting(containerEl).setName("Destination mode").setDesc("Choose one inbox file or a dated daily-note folder.").addDropdown((dropdown) => dropdown.addOptions({ inbox: "Inbox file", daily: "Daily note" }).setValue(this.plugin.settings.destinationMode).onChange(async (value) => {
      this.plugin.settings.destinationMode = value;
      await this.plugin.persist();
      this.display();
    }));
    new import_obsidian.Setting(containerEl).setName("Inbox file").setDesc("Relative Markdown path used in inbox mode.").addText((text) => text.setValue(this.plugin.settings.inboxPath).onChange(async (value) => {
      this.plugin.settings.inboxPath = normalizeVaultPath(value) || DEFAULT_SETTINGS.inboxPath;
      await this.plugin.persist();
    }));
    new import_obsidian.Setting(containerEl).setName("Daily-note folder").setDesc("Relative folder used in daily-note mode.").addText((text) => text.setValue(this.plugin.settings.dailyFolder).onChange(async (value) => {
      this.plugin.settings.dailyFolder = normalizeVaultPath(value);
      await this.plugin.persist();
    }));
    new import_obsidian.Setting(containerEl).setName("Daily-note format").setDesc("Filename format: YYYY, MM, DD, HH, mm, ss.").addText((text) => text.setValue(this.plugin.settings.dailyFormat).onChange(async (value) => {
      this.plugin.settings.dailyFormat = value || DEFAULT_SETTINGS.dailyFormat;
      await this.plugin.persist();
    }));
    new import_obsidian.Setting(containerEl).setName("Timestamp format").setDesc("Template time format: YYYY, MM, DD, HH, mm, ss.").addText((text) => text.setValue(this.plugin.settings.timestampFormat).onChange(async (value) => {
      this.plugin.settings.timestampFormat = value || DEFAULT_SETTINGS.timestampFormat;
      await this.plugin.persist();
    }));
    new import_obsidian.Setting(containerEl).setName("Capture template").setDesc("Use {{time}}, {{source}}, {{text}}, and {{id}}. The id marker prevents duplicate retries.").addTextArea((text) => text.setValue(this.plugin.settings.template).onChange(async (value) => {
      this.plugin.settings.template = value || DEFAULT_TEMPLATE;
      await this.plugin.persist();
    }));
    new import_obsidian.Setting(containerEl).setName("Create missing destinations").setDesc("Off by default. When enabled, Kairo may create the configured Markdown file after an explicit setup/test action or capture.").addToggle((toggle) => toggle.setValue(this.plugin.settings.createMissing).onChange(async (value) => {
      this.plugin.settings.createMissing = value;
      await this.plugin.persist();
    }));
    new import_obsidian.Setting(containerEl).setName("Close after saving").setDesc("Close the scratchpad after a successful save.").addToggle((toggle) => toggle.setValue(this.plugin.settings.closeAfterSaving).onChange(async (value) => {
      this.plugin.settings.closeAfterSaving = value;
      await this.plugin.persist();
    }));
    new import_obsidian.Setting(containerEl).setName("Launch at login").setDesc("Optional desktop convenience. Disabled by default and handled locally by Electron when supported.").addToggle((toggle) => toggle.setValue(this.plugin.settings.launchAtLogin).onChange(async (value) => {
      this.plugin.settings.launchAtLogin = value;
      this.plugin.applyLaunchAtLogin();
      await this.plugin.persist();
    }));
    new import_obsidian.Setting(containerEl).setName("Queue").setDesc(`${this.plugin.queue.length} capture${this.plugin.queue.length === 1 ? "" : "s"} waiting for delivery.`).addButton((button) => button.setButtonText("Show queue").onClick(() => new QueueModal(this.app, this.plugin).open())).addButton((button) => button.setButtonText("Flush now").onClick(() => void this.plugin.flushQueue(true)));
    new import_obsidian.Setting(containerEl).setName("First-run setup").setDesc(this.plugin.settings.setupCompleted ? "Setup has been completed." : "Validate the destination and write a confirmed test capture.").addButton((button) => button.setButtonText("Open setup").onClick(() => new SetupModal(this.app, this.plugin).open()));
  }
};
