/* Generated by esbuild. See main.ts for source. */
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => KairoQuickCapturePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/core.ts
function formatTimestamp(date, format) {
  const pad = (value) => String(value).padStart(2, "0");
  const replacements = {
    YYYY: String(date.getFullYear()),
    MM: pad(date.getMonth() + 1),
    DD: pad(date.getDate()),
    HH: pad(date.getHours()),
    mm: pad(date.getMinutes()),
    ss: pad(date.getSeconds())
  };
  return format.replace(/YYYY|MM|DD|HH|mm|ss/g, (token) => replacements[token]);
}
function renderTemplate(template, context) {
  return template.replace(/\{\{\s*(time|source|text|id)\s*\}\}/gi, (_, key) => {
    const normalized = key.toLowerCase();
    return context[normalized];
  });
}
function normalizeVaultPath(path) {
  return path.trim().replace(/\\/g, "/").replace(/^\/+|\/+$/g, "");
}
function joinVaultPath(folder, file) {
  const left = normalizeVaultPath(folder);
  const right = normalizeVaultPath(file);
  return [left, right].filter(Boolean).join("/");
}
function dailyNotePath(folder, date, format) {
  return joinVaultPath(folder, `${formatTimestamp(date, format)}.md`);
}
function appendText(existing, entry) {
  if (!existing) return entry;
  const separator = existing.endsWith("\n") ? "" : "\n";
  return `${existing}${separator}${entry}`;
}
function diagnosticSummary(destination, error, queueId) {
  const message = error instanceof Error ? error.message : String(error);
  return `Kairo could not deliver capture ${queueId}. Destination: ${destination}. Reason: ${message}`;
}

// src/billing.ts
var import_obsidian2 = require("obsidian");

// src/constance-account.ts
var import_obsidian = require("obsidian");
var CONSTANCE_ACCOUNT_BASE_URL = "https://app.tutivsoft.com";
function errorDetail(response, fallback) {
  var _a, _b;
  return String(((_a = response.json) == null ? void 0 : _a.detail) || ((_b = response.json) == null ? void 0 : _b.message) || response.text || fallback);
}
async function authenticate(mode, email, password, installationId) {
  var _a, _b;
  const body = mode === "register" ? { email, password, external_customer_id: installationId } : { email, password };
  const response = await (0, import_obsidian.requestUrl)({
    url: `${CONSTANCE_ACCOUNT_BASE_URL}/api/v1/auth/${mode}`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
    throw: false
  });
  if (response.status < 200 || response.status >= 300) {
    throw new Error(errorDetail(response, `Billing ${mode} failed (HTTP ${response.status})`));
  }
  const token = String(((_a = response.json) == null ? void 0 : _a.access_token) || "");
  if (token) return { accessToken: token };
  if (((_b = response.json) == null ? void 0 : _b.verification_required) === true) return { verificationRequired: true };
  throw new Error("Constance did not return an account token.");
}
async function linkInstallation(adapter, token) {
  const response = await (0, import_obsidian.requestUrl)({
    url: `${CONSTANCE_ACCOUNT_BASE_URL}/api/v1/billing/installations/link`,
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
    body: JSON.stringify({
      app_id: adapter.appId,
      installation_id: adapter.installationId,
      legacy_external_customer_id: adapter.installationId,
      platform: "obsidian",
      app_version: adapter.appVersion || void 0
    }),
    throw: false
  });
  if (response.status < 200 || response.status >= 300) {
    throw new Error(errorDetail(response, `Installation link failed (HTTP ${response.status})`));
  }
}
async function signInBillingAccount(adapter, password, mode) {
  const email = adapter.state.billingEmail.trim().toLowerCase();
  if (!email || !email.includes("@")) throw new Error("Enter a valid billing email.");
  if (password.length < 8) throw new Error("Password must contain at least 8 characters.");
  if (!adapter.installationId) throw new Error("The plugin installation ID is not ready.");
  const result = await authenticate(mode, email, password, adapter.installationId);
  if (!result.accessToken) {
    throw new Error("Account created. Check your email for the verification token, then use Verify account.");
  }
  await completeBillingSignIn(adapter, email, result.accessToken);
}
async function completeBillingSignIn(adapter, email, token) {
  await linkInstallation(adapter, token);
  adapter.state.billingEmail = email;
  adapter.state.billingAccessToken = token;
  adapter.state.billingAccountLinked = true;
  await adapter.persist();
  await adapter.syncBalance();
}
async function verifyBillingAccount(adapter, verificationToken) {
  var _a;
  const token = verificationToken.trim();
  if (!token) throw new Error("Enter the verification token from your billing email.");
  const response = await (0, import_obsidian.requestUrl)({
    url: `${CONSTANCE_ACCOUNT_BASE_URL}/api/v1/auth/register/verify`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ token }),
    throw: false
  });
  if (response.status < 200 || response.status >= 300) {
    throw new Error(errorDetail(response, `Billing account verification failed (HTTP ${response.status})`));
  }
  const accessToken = String(((_a = response.json) == null ? void 0 : _a.access_token) || "");
  if (!accessToken) throw new Error("Constance did not return an account token after verification.");
  await completeBillingSignIn(adapter, adapter.state.billingEmail.trim().toLowerCase(), accessToken);
}
async function claimAccountFreeUsage(state, appId, installationId, eventId, amount) {
  var _a, _b;
  if (!state.billingAccessToken || !state.billingAccountLinked) return { kind: "auth-required" };
  try {
    const response = await (0, import_obsidian.requestUrl)({
      url: `${CONSTANCE_ACCOUNT_BASE_URL}/api/v1/billing/free-usage/claim`,
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${state.billingAccessToken}` },
      body: JSON.stringify({ app_id: appId, installation_id: installationId, event_id: eventId, amount }),
      throw: false
    });
    if (response.status === 402) return { kind: "insufficient" };
    if (response.status === 401 || response.status === 403 || response.status === 404) return { kind: "auth-required" };
    if (response.status < 200 || response.status >= 300) return { kind: "error" };
    return { kind: "ok", remaining: Math.max(0, Number((_b = (_a = response.json) == null ? void 0 : _a.data) == null ? void 0 : _b.remaining) || 0) };
  } catch (error) {
    console.error("Constance account free-usage claim failed", error);
    return { kind: "error" };
  }
}
async function spendAccountCredits(state, appId, installationId, eventId, amount) {
  var _a, _b, _c;
  if (!state.billingAccessToken || !state.billingAccountLinked) return { kind: "auth-required" };
  try {
    const response = await (0, import_obsidian.requestUrl)({
      url: `${CONSTANCE_ACCOUNT_BASE_URL}/api/v1/billing/credits/spend`,
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${state.billingAccessToken}` },
      body: JSON.stringify({ app_id: appId, installation_id: installationId, event_id: eventId, amount }),
      throw: false
    });
    if (response.status === 402) return { kind: "insufficient" };
    if (response.status === 401 || response.status === 403 || response.status === 404) return { kind: "auth-required" };
    if (response.status < 200 || response.status >= 300) return { kind: "error" };
    const balance = Number((_c = (_b = (_a = response.json) == null ? void 0 : _a.data) == null ? void 0 : _b.credits) == null ? void 0 : _c.balance);
    return Number.isFinite(balance) ? { kind: "ok", balance: Math.max(0, balance) } : { kind: "error" };
  } catch (error) {
    console.error("Constance authenticated credit spend failed", error);
    return { kind: "error" };
  }
}
function addBillingAccountSettings(containerEl, adapter) {
  let password = "";
  let verificationToken = "";
  new import_obsidian.Setting(containerEl).setName("Billing account email").setDesc("Used for sign-in, purchase restore, and checkout. Reinstalling no longer creates a new free allowance.").addText((text) => text.setPlaceholder("you@example.com").setValue(adapter.state.billingEmail).onChange(async (value) => {
    adapter.state.billingEmail = value.trim();
    await adapter.persist();
  }));
  new import_obsidian.Setting(containerEl).setName("Billing account password").setDesc("Used only for this sign-in request. The password is never saved by the plugin.").addText((text) => {
    text.inputEl.type = "password";
    text.setPlaceholder("At least 8 characters").onChange((value) => {
      password = value;
    });
  });
  new import_obsidian.Setting(containerEl).setName("Email verification token").setDesc("After creating an account, enter the one-time token sent by email, then verify it.").addText((text) => {
    text.inputEl.type = "password";
    text.setPlaceholder("Paste token").onChange((value) => {
      verificationToken = value.trim();
    });
  });
  const status = adapter.state.billingAccountLinked ? "Signed in and linked" : "Not signed in";
  new import_obsidian.Setting(containerEl).setName("Billing account").setDesc(`${status}. The saved bearer session can restore purchases; your password is not stored.`).addButton((button) => button.setButtonText("Sign in").onClick(async () => {
    var _a;
    button.setDisabled(true);
    try {
      await signInBillingAccount(adapter, password, "login");
      new import_obsidian.Notice("Billing account signed in and this installation was linked.");
      (_a = adapter.refresh) == null ? void 0 : _a.call(adapter);
    } catch (error) {
      new import_obsidian.Notice(error instanceof Error ? error.message : "Billing sign-in failed.");
    } finally {
      button.setDisabled(false);
    }
  })).addButton((button) => button.setButtonText("Create account").onClick(async () => {
    var _a;
    button.setDisabled(true);
    try {
      await signInBillingAccount(adapter, password, "register");
      new import_obsidian.Notice("Billing account created and this installation was linked.");
      (_a = adapter.refresh) == null ? void 0 : _a.call(adapter);
    } catch (error) {
      new import_obsidian.Notice(error instanceof Error ? error.message : "Billing account creation failed.");
    } finally {
      button.setDisabled(false);
    }
  })).addButton((button) => button.setButtonText("Verify account").onClick(async () => {
    var _a;
    button.setDisabled(true);
    try {
      await verifyBillingAccount(adapter, verificationToken);
      new import_obsidian.Notice("Billing account verified and this installation was linked.");
      (_a = adapter.refresh) == null ? void 0 : _a.call(adapter);
    } catch (error) {
      new import_obsidian.Notice(error instanceof Error ? error.message : "Billing account verification failed.");
    } finally {
      button.setDisabled(false);
    }
  })).addButton((button) => button.setButtonText("Sign out").setDisabled(!adapter.state.billingAccessToken).onClick(async () => {
    var _a;
    adapter.state.billingAccessToken = "";
    adapter.state.billingAccountLinked = false;
    await adapter.persist();
    new import_obsidian.Notice("Billing account signed out on this installation.");
    (_a = adapter.refresh) == null ? void 0 : _a.call(adapter);
  }));
}

// src/billing.ts
var CONSTANCE_BASE_URL = "https://app.tutivsoft.com";
var CONSTANCE_APP_ID = "kairo-quick-capture";
var FREE_USES_PER_DAY = 3;
var CONSTANCE_PRICE_IDS = {
  usd_001: "pri_01m28hknyche7mcq4vdgjcp4x6",
  // $1 -> 100 uses
  usd_010: "pri_01m28hkppkk8m3dy56gmmbnrst"
  // $10 -> 1,000 uses
};
var CONSTANCE_PLAN_CODES = {
  usd_001: "one_time",
  usd_010: "standard"
};
var billingLocks = /* @__PURE__ */ new WeakMap();
function withBillingLock(plugin, work) {
  var _a;
  const previous = (_a = billingLocks.get(plugin)) != null ? _a : Promise.resolve();
  const current = previous.catch(() => void 0).then(work);
  billingLocks.set(plugin, current);
  return current.finally(() => {
    if (billingLocks.get(plugin) === current) billingLocks.delete(plugin);
  });
}
function currentDayKey(date = /* @__PURE__ */ new Date()) {
  const pad = (value) => String(value).padStart(2, "0");
  return `${date.getUTCFullYear()}-${pad(date.getUTCMonth() + 1)}-${pad(date.getUTCDate())}`;
}
function generateSecureDeviceId() {
  const bytes = new Uint8Array(16);
  window.crypto.getRandomValues(bytes);
  return Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join("");
}
function generateEventId() {
  const bytes = new Uint8Array(12);
  window.crypto.getRandomValues(bytes);
  return `evt_${Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join("")}`;
}
function normalizeBillingSettings(settings, date = /* @__PURE__ */ new Date()) {
  settings.constanceDeviceId = typeof settings.constanceDeviceId === "string" ? settings.constanceDeviceId : "";
  settings.billingEmail = typeof settings.billingEmail === "string" ? settings.billingEmail : "";
  settings.billingAccessToken = typeof settings.billingAccessToken === "string" ? settings.billingAccessToken : "";
  settings.billingAccountLinked = settings.billingAccountLinked === true && Boolean(settings.billingAccessToken);
  settings.freeUsesRemaining = Number.isFinite(settings.freeUsesRemaining) ? Math.max(0, Math.min(FREE_USES_PER_DAY, Math.trunc(settings.freeUsesRemaining))) : FREE_USES_PER_DAY;
  settings.purchasedUses = Number.isFinite(settings.purchasedUses) ? Math.max(0, Math.trunc(settings.purchasedUses)) : 0;
  settings.pendingSpendEvents = Array.isArray(settings.pendingSpendEvents) ? settings.pendingSpendEvents.filter((item) => item && typeof item.eventId === "string" && Number.isInteger(item.amount) && item.amount > 0) : [];
  if (typeof settings.freeUsesDay !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(settings.freeUsesDay)) {
    settings.freeUsesDay = currentDayKey(date);
    settings.freeUsesRemaining = FREE_USES_PER_DAY;
  }
  resetFreeUsesIfNeeded(settings, date);
}
function resetFreeUsesIfNeeded(settings, date = /* @__PURE__ */ new Date()) {
  const today = currentDayKey(date);
  if (settings.freeUsesDay !== today) {
    settings.freeUsesDay = today;
    settings.freeUsesRemaining = FREE_USES_PER_DAY;
  }
}
async function fetchEntitlements(plugin) {
  var _a, _b;
  const response = await (0, import_obsidian2.requestUrl)({
    url: `${CONSTANCE_BASE_URL}/api/v1/billing/entitlements/me?${new URLSearchParams({ app_id: CONSTANCE_APP_ID, installation_id: plugin.settings.constanceDeviceId }).toString()}`,
    method: "GET",
    headers: { Authorization: `Bearer ${plugin.settings.billingAccessToken}` },
    throw: false
  });
  if (response.status < 200 || response.status >= 300) throw new Error(`Entitlement sync failed: HTTP ${response.status}`);
  const data = (_a = response.json) == null ? void 0 : _a.data;
  const freeUsage = data == null ? void 0 : data.free_usage;
  const freeRemaining = Number(freeUsage == null ? void 0 : freeUsage.remaining);
  const freeDay = typeof (freeUsage == null ? void 0 : freeUsage.period_key) === "string" && /^\d{4}-\d{2}-\d{2}$/.test(freeUsage.period_key) ? freeUsage.period_key : void 0;
  return {
    purchasedUses: Math.max(0, Number((_b = data == null ? void 0 : data.credits) == null ? void 0 : _b.balance) || 0),
    freeUsesRemaining: Number.isFinite(freeRemaining) ? Math.max(0, Math.min(FREE_USES_PER_DAY, Math.trunc(freeRemaining))) : void 0,
    freeUsesDay: freeDay
  };
}
async function syncPurchasedUses(plugin) {
  return withBillingLock(plugin, async () => {
    if (!plugin.settings.constanceDeviceId) return;
    try {
      if (!plugin.settings.billingAccessToken || !plugin.settings.billingAccountLinked) return;
      const snapshot = await fetchEntitlements(plugin);
      plugin.settings.purchasedUses = snapshot.purchasedUses;
      if (snapshot.freeUsesRemaining !== void 0) plugin.settings.freeUsesRemaining = snapshot.freeUsesRemaining;
      if (snapshot.freeUsesDay) plugin.settings.freeUsesDay = snapshot.freeUsesDay;
      await plugin.persist();
    } catch (error) {
      console.error("Kairo: Constance entitlement sync failed", error);
    }
  });
}
async function retryPendingSpendEvents(plugin) {
  var _a;
  for (const pending of [...(_a = plugin.settings.pendingSpendEvents) != null ? _a : []]) {
    const result = await spendConstanceUse(plugin, pending.eventId);
    if (result.kind === "error") break;
    plugin.settings.pendingSpendEvents = plugin.settings.pendingSpendEvents.filter((item) => item.eventId !== pending.eventId);
    plugin.settings.purchasedUses = result.kind === "ok" ? result.balance : 0;
    await plugin.persist();
  }
}
async function spendConstanceUse(plugin, eventId = generateEventId()) {
  const result = await spendAccountCredits(plugin.settings, CONSTANCE_APP_ID, plugin.settings.constanceDeviceId, eventId, 1);
  if (result.kind === "auth-required") {
    plugin.settings.billingAccessToken = "";
    plugin.settings.billingAccountLinked = false;
    await plugin.persist();
    return { kind: "error" };
  }
  return result.kind === "ok" || result.kind === "insufficient" || result.kind === "error" ? result : { kind: "error" };
}
async function consumeCaptureUse(plugin, eventId = generateEventId()) {
  return withBillingLock(plugin, async () => {
    var _a;
    if (!plugin.settings.billingAccessToken || !plugin.settings.billingAccountLinked) {
      new import_obsidian2.Notice("Kairo: sign in or create a billing account in plugin settings before capturing.");
      return false;
    }
    const free = await claimAccountFreeUsage(plugin.settings, CONSTANCE_APP_ID, plugin.settings.constanceDeviceId, eventId, 1);
    if (free.kind === "ok") {
      plugin.settings.freeUsesDay = currentDayKey();
      plugin.settings.freeUsesRemaining = free.remaining;
      await plugin.persist();
      return true;
    }
    if (free.kind === "auth-required") {
      plugin.settings.billingAccessToken = "";
      plugin.settings.billingAccountLinked = false;
      await plugin.persist();
      new import_obsidian2.Notice("Kairo: your billing session expired. Sign in again in plugin settings.");
      return false;
    }
    if (free.kind === "error") {
      new import_obsidian2.Notice("Kairo: the account allowance could not be verified. Nothing was captured.");
      return false;
    }
    plugin.settings.pendingSpendEvents = (_a = plugin.settings.pendingSpendEvents) != null ? _a : [];
    await retryPendingSpendEvents(plugin);
    if (plugin.settings.pendingSpendEvents.length > 0) {
      new import_obsidian2.Notice("Kairo: a previous capture spend is still being reconciled. Try again when the connection is restored.");
      return false;
    }
    plugin.settings.pendingSpendEvents.push({ eventId, amount: 1 });
    await plugin.persist();
    const result = await spendConstanceUse(plugin, eventId);
    if (result.kind === "ok") {
      plugin.settings.purchasedUses = result.balance;
      plugin.settings.pendingSpendEvents = plugin.settings.pendingSpendEvents.filter((item) => item.eventId !== eventId);
      await plugin.persist();
      return true;
    }
    if (result.kind === "insufficient") {
      plugin.settings.purchasedUses = 0;
      plugin.settings.pendingSpendEvents = plugin.settings.pendingSpendEvents.filter((item) => item.eventId !== eventId);
      await plugin.persist();
      new import_obsidian2.Notice("Kairo: no uses remain. Buy a use pack in plugin settings.");
      return false;
    }
    new import_obsidian2.Notice("Kairo: billing could not be verified. Nothing was captured.");
    return false;
  });
}
async function createAuthenticatedCheckout(plugin, tier) {
  var _a;
  const idempotencyKey = `checkout_${generateEventId()}`;
  const response = await (0, import_obsidian2.requestUrl)({
    url: `${CONSTANCE_BASE_URL}/api/v1/billing/checkout`,
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${plugin.settings.billingAccessToken}`, "Idempotency-Key": idempotencyKey },
    body: JSON.stringify({
      app_id: CONSTANCE_APP_ID,
      plan_code: CONSTANCE_PLAN_CODES[tier],
      installation_id: plugin.settings.constanceDeviceId,
      quantity: 1,
      coupon_code: null
    }),
    throw: false
  });
  if (response.status === 401 || response.status === 403) return { kind: "auth-required" };
  if (response.status < 200 || response.status >= 300) return { kind: "fallback" };
  const data = (_a = response.json) == null ? void 0 : _a.data;
  const checkoutUrl = typeof (data == null ? void 0 : data.checkout_url) === "string" ? data.checkout_url : "";
  return checkoutUrl ? { kind: "ok", checkoutUrl, checkoutId: (data == null ? void 0 : data.checkout_id) ? String(data.checkout_id) : void 0 } : { kind: "fallback" };
}
async function pollAuthenticatedCheckout(plugin, checkoutId) {
  var _a, _b;
  if (!plugin.settings.billingAccessToken || !plugin.settings.billingAccountLinked) return false;
  const response = await (0, import_obsidian2.requestUrl)({
    url: `${CONSTANCE_BASE_URL}/api/v1/billing/checkouts/${encodeURIComponent(checkoutId)}`,
    method: "GET",
    headers: { Authorization: `Bearer ${plugin.settings.billingAccessToken}` },
    throw: false
  });
  return response.status >= 200 && response.status < 300 && ((_b = (_a = response.json) == null ? void 0 : _a.data) == null ? void 0 : _b.settled) === true;
}
function openBuyCheckout(plugin, tier) {
  if (!plugin.settings.billingAccessToken || !plugin.settings.billingAccountLinked) {
    new import_obsidian2.Notice("Sign in or create a billing account in Kairo settings before buying uses.");
    return;
  }
  const priceId = CONSTANCE_PRICE_IDS[tier];
  void (async () => {
    var _a, _b;
    try {
      const checkout = await createAuthenticatedCheckout(plugin, tier);
      if (checkout.kind === "ok") {
        window.open(checkout.checkoutUrl, "_blank");
        (_a = plugin.pollAfterCheckout) == null ? void 0 : _a.call(plugin, checkout.checkoutId);
        return;
      }
      if (checkout.kind === "auth-required") {
        plugin.settings.billingAccessToken = "";
        plugin.settings.billingAccountLinked = false;
        await plugin.persist();
        new import_obsidian2.Notice("Kairo: your billing session expired. Sign in again before buying uses.");
        return;
      }
    } catch (error) {
      console.error("Kairo: authenticated checkout request failed", error);
      new import_obsidian2.Notice("Kairo: checkout status is unknown. Refresh billing and try again.");
      return;
    }
    const email = plugin.settings.billingEmail.trim();
    if (!priceId.startsWith("pri_")) {
      new import_obsidian2.Notice("Kairo billing is not available for this pack yet.");
      return;
    }
    if (!email || !email.includes("@")) {
      new import_obsidian2.Notice("Enter a valid billing email in Kairo settings before using the legacy checkout fallback.");
      return;
    }
    const params = new URLSearchParams({ app_id: CONSTANCE_APP_ID, price_id: priceId, email, external_customer_id: plugin.settings.constanceDeviceId });
    window.open(`${CONSTANCE_BASE_URL}/buy?${params.toString()}`, "_blank");
    (_b = plugin.pollAfterCheckout) == null ? void 0 : _b.call(plugin);
  })();
}

// src/plugin-support.ts
var import_obsidian3 = require("obsidian");
var SAFE_DETAIL_KEYS = /* @__PURE__ */ new Set([
  "version",
  "operation",
  "scope",
  "selectedCount",
  "total",
  "changed",
  "skipped",
  "failed",
  "unchanged",
  "reviewEnabled",
  "fieldCount",
  "noteChars",
  "httpStatus",
  "errorType",
  "outcome",
  "restored",
  "authorizationSource",
  "cancelled",
  "line",
  "column",
  "settingCount",
  "attempt",
  "attempts",
  "queueCount",
  "itemCount",
  "fileCount",
  "imageCount",
  "stage",
  "category",
  "status",
  "durationMs",
  "elapsedMs"
]);
function safeString(value) {
  if (value.length <= 120 && /^[A-Za-z0-9 _=.,:-]*$/.test(value) && !/(?:sk-[A-Za-z0-9]|bearer|api.?key|token|secret)/i.test(value)) {
    return value;
  }
  return "[omitted]";
}
function safeDetail(value) {
  if (value instanceof Error) return JSON.stringify({ errorType: safeString(value.name || "Error") });
  if (!value || typeof value !== "object" || Array.isArray(value)) return "[detail omitted]";
  const safe = {};
  for (const [key, item] of Object.entries(value)) {
    if (!SAFE_DETAIL_KEYS.has(key)) continue;
    if (typeof item === "string") safe[key] = safeString(item);
    else if (typeof item === "number" && Number.isFinite(item)) safe[key] = item;
    else if (typeof item === "boolean" || item === null) safe[key] = item;
  }
  return JSON.stringify(safe);
}
function safeErrorType(error) {
  if (error instanceof Error) return safeString(error.name || "Error");
  return safeString(typeof error);
}
var DocumentationModal = class extends import_obsidian3.Modal {
  constructor(app, docs) {
    super(app);
    this.docs = docs;
  }
  onOpen() {
    this.titleEl.setText(this.docs.name + " documentation");
    this.contentEl.createEl("p", { text: this.docs.summary });
    const addSection = (title, items) => {
      this.contentEl.createEl("h3", { text: title });
      const list = this.contentEl.createEl("ol");
      for (const item of items) list.createEl("li", { text: item });
    };
    addSection("Quick start", this.docs.quickStart);
    addSection("Useful commands", Array.from(/* @__PURE__ */ new Set([...this.docs.commands, "Copy full debug log"])));
    addSection("Troubleshooting", this.docs.troubleshooting);
  }
  onClose() {
    this.contentEl.empty();
  }
};
var PluginSupport = class {
  constructor(plugin, docs) {
    this.plugin = plugin;
    this.docs = docs;
    this.entries = [];
    this.maxEntries = 1e3;
    this.droppedEntries = 0;
    this.started = false;
  }
  start() {
    if (this.started) return;
    this.started = true;
    this.info("plugin.loaded", { version: this.plugin.manifest.version });
    this.plugin.registerDomEvent(window, "error", (event) => {
      const error = event.error;
      this.error("runtime.error", {
        errorType: error instanceof Error ? error.name : "ErrorEvent",
        line: event.lineno,
        column: event.colno
      });
    });
    this.plugin.registerDomEvent(window, "unhandledrejection", (event) => {
      this.error("runtime.unhandled_rejection", { errorType: safeErrorType(event.reason) });
    });
    const addCommand = this.plugin.addCommand.bind(this.plugin);
    const registerCommand = (command) => addCommand(this.instrumentCommand(command));
    registerCommand({
      id: "open-documentation",
      name: "Open documentation",
      callback: () => new DocumentationModal(this.plugin.app, this.docs).open()
    });
    registerCommand({
      id: "copy-debug-log",
      name: "Copy full debug log",
      callback: () => this.copyDiagnostics()
    });
    registerCommand({
      id: "open-plugin-settings",
      name: "Open plugin settings",
      callback: () => {
        const setting = this.plugin.app.setting;
        setting == null ? void 0 : setting.open();
        setting == null ? void 0 : setting.openTabById(this.plugin.manifest.id);
      }
    });
    this.instrumentFutureCommands(addCommand);
  }
  info(event, detail) {
    this.record("info", event, detail);
  }
  warn(event, detail) {
    this.record("warn", event, detail);
  }
  error(event, detail) {
    this.record("error", event, detail);
  }
  addDiagnosticsSetting(containerEl) {
    new import_obsidian3.Setting(containerEl).setName("Diagnostics").setDesc("Copy up to the latest 1,000 events recorded by this plugin. Logs reset when the plugin reloads. Note contents, paths, credentials, and raw error messages are excluded.").addButton((button) => button.setButtonText("Copy full log").onClick(() => {
      void this.copyDiagnostics();
    }));
  }
  instrumentFutureCommands(addCommand) {
    const originalDescriptor = Object.getOwnPropertyDescriptor(this.plugin, "addCommand");
    Object.defineProperty(this.plugin, "addCommand", {
      configurable: true,
      writable: true,
      value: (command) => addCommand(this.instrumentCommand(command))
    });
    this.plugin.register(() => {
      if (originalDescriptor) Object.defineProperty(this.plugin, "addCommand", originalDescriptor);
      else Reflect.deleteProperty(this.plugin, "addCommand");
    });
  }
  instrumentCommand(command) {
    const instrument = (callback) => (...args) => this.trackCommand(command.id, () => callback.apply(command, args));
    return {
      ...command,
      callback: command.callback ? instrument(command.callback) : void 0,
      editorCallback: command.editorCallback ? instrument(command.editorCallback) : void 0,
      checkCallback: command.checkCallback ? (checking) => checking ? command.checkCallback(checking) : this.trackCommand(command.id, () => command.checkCallback(checking)) : void 0,
      editorCheckCallback: command.editorCheckCallback ? (checking, editor, context) => checking ? command.editorCheckCallback(checking, editor, context) : this.trackCommand(command.id, () => command.editorCheckCallback(checking, editor, context)) : void 0
    };
  }
  trackCommand(commandId, action) {
    const startedAt = Date.now();
    this.info("command.started", { operation: commandId });
    try {
      const result = action();
      if (result && typeof result.then === "function") {
        return Promise.resolve(result).then(
          (value) => {
            this.info("command.completed", { operation: commandId, durationMs: Date.now() - startedAt });
            return value;
          },
          (error) => {
            this.error("command.failed", { operation: commandId, errorType: safeErrorType(error), durationMs: Date.now() - startedAt });
            throw error;
          }
        );
      }
      this.info("command.completed", { operation: commandId, durationMs: Date.now() - startedAt });
      return result;
    } catch (error) {
      this.error("command.failed", { operation: commandId, errorType: safeErrorType(error), durationMs: Date.now() - startedAt });
      throw error;
    }
  }
  record(level, event, detail) {
    var _a;
    const safeEvent = /^[a-z0-9][a-z0-9._-]{0,99}$/i.test(event) ? event : "invalid_event";
    const entry = { at: (/* @__PURE__ */ new Date()).toISOString(), level, event: safeEvent };
    if (detail !== void 0) entry.detail = safeDetail(detail);
    this.entries.push(entry);
    if (this.entries.length > this.maxEntries) {
      const removed = this.entries.length - this.maxEntries;
      this.entries.splice(0, removed);
      this.droppedEntries += removed;
    }
    const method = level === "error" ? console.error : level === "warn" ? console.warn : console.info;
    method.call(console, "[" + this.docs.name + "] " + entry.event, (_a = entry.detail) != null ? _a : "");
  }
  async copyDiagnostics() {
    this.info("diagnostics.copy_requested", { total: this.entries.length + 1 });
    const captured = (/* @__PURE__ */ new Date()).toISOString();
    const snapshot = this.entries.slice();
    const header = [
      "Plugin debug log",
      "Log scope: this plugin, since its most recent load",
      "Plugin: " + this.docs.name,
      "Plugin ID: " + this.plugin.manifest.id,
      "Version: " + this.plugin.manifest.version,
      "Captured: " + captured,
      "User agent: " + navigator.userAgent,
      "Events included: " + snapshot.length,
      "Older events omitted: " + this.droppedEntries,
      ""
    ];
    const text = header.concat(snapshot.map(
      (entry) => entry.at + " [" + entry.level.toUpperCase() + "] " + entry.event + (entry.detail ? " \u2014 " + entry.detail : "")
    )).join("\n");
    try {
      await navigator.clipboard.writeText(text);
      this.info("diagnostics.copy_succeeded", { total: snapshot.length });
      const omitted = this.droppedEntries ? "; " + this.droppedEntries + " older events omitted" : "";
      new import_obsidian3.Notice(this.docs.name + ": copied " + snapshot.length + " log events" + omitted + ".");
    } catch (error) {
      this.error("diagnostics.copy_failed", { errorType: safeErrorType(error) });
      new import_obsidian3.Notice(this.docs.name + ": could not copy the debug log.");
    }
  }
};

// main.ts
var DEFAULT_TEMPLATE = "- {{time}} \u2014 {{text}}\n";
var DEFAULT_SETTINGS = {
  shortcut: "Ctrl+Shift+Space",
  vaultFolder: "",
  destinationMode: "inbox",
  inboxPath: "Inbox.md",
  dailyFolder: "Daily",
  dailyFormat: "YYYY-MM-DD",
  template: DEFAULT_TEMPLATE,
  timestampFormat: "YYYY-MM-DD HH:mm",
  createMissing: false,
  closeAfterSaving: true,
  launchAtLogin: false,
  constanceDeviceId: "",
  billingEmail: "",
  billingAccessToken: "",
  billingAccountLinked: false,
  freeUsesRemaining: 3,
  freeUsesDay: currentDayKey(),
  purchasedUses: 0,
  pendingSpendEvents: []
};
var DestinationChangedError = class extends Error {
  constructor() {
    super("The destination changed while Kairo was preparing the append. Nothing was overwritten.");
    this.name = "DestinationChangedError";
  }
};
var KairoQuickCapturePlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.queue = [];
    this.persistChain = Promise.resolve();
    this.deliveryChain = Promise.resolve();
  }
  async onload() {
    var _a;
    this.support = new PluginSupport(this, { name: "Kairo Quick Capture", summary: "Capture ideas quickly to an inbox or daily note, including while the target is unavailable.", quickStart: ["Sign in to billing in Settings.", "Run Quick capture.", "Type the capture and submit; Kairo chooses the configured default destination."], commands: ["Quick capture", "Show capture queue", "Flush queue"], troubleshooting: ["Use Copy debug log before reporting a problem.", "Check the configured destination when queued captures do not flush."] });
    this.support.start();
    const data = await this.loadData();
    this.settings = { ...DEFAULT_SETTINGS, ...(_a = data == null ? void 0 : data.settings) != null ? _a : {} };
    this.queue = Array.isArray(data == null ? void 0 : data.queue) ? data.queue : [];
    if (!this.settings.constanceDeviceId) this.settings.constanceDeviceId = generateSecureDeviceId();
    normalizeBillingSettings(this.settings);
    await this.persist();
    this.addCommand({
      id: "open-capture",
      name: "Open quick capture",
      hotkeys: [{ modifiers: ["Mod", "Shift"], key: "K" }],
      callback: () => this.openCapture()
    });
    this.registerEvent(this.app.workspace.on("editor-menu", (menu, editor, info) => this.addEditorMenuItems(menu, editor, info.file)));
    this.registerEvent(this.app.workspace.on("file-menu", (menu, file) => this.addFileMenuItems(menu, file)));
    this.registerEvent(this.app.workspace.on("files-menu", (menu, files) => this.addFilesMenuItems(menu, files)));
    this.addCommand({
      id: "flush-queue",
      name: "Flush queued captures",
      callback: () => this.flushQueue(true)
    });
    this.addCommand({
      id: "show-queue",
      name: "Show queued captures",
      callback: () => new QueueModal(this.app, this).open()
    });
    this.addSettingTab(new KairoSettingTab(this.app, this));
    this.registerInterval(window.setInterval(() => void this.flushQueue(false), 6e4));
    this.app.workspace.onLayoutReady(() => {
      this.registerGlobalShortcut();
      void this.flushQueue(false);
      void syncPurchasedUses(this).then(() => retryPendingSpendEvents(this));
    });
  }
  onunload() {
    this.unregisterGlobalShortcut();
    if (this.checkoutPollTimer !== void 0) window.clearInterval(this.checkoutPollTimer);
  }
  async persist() {
    const snapshot = {
      settings: { ...this.settings },
      queue: this.queue.map((item) => ({ ...item }))
    };
    const write = this.persistChain.catch(() => void 0).then(() => this.saveData(snapshot));
    this.persistChain = write;
    await write;
  }
  openCapture(initialText = "") {
    new CaptureModal(this.app, this, initialText).open();
  }
  addEditorMenuItems(menu, editor, file) {
    const selection = editor.getSelection().trim();
    if (selection) menu.addItem((item) => item.setTitle("Kairo: Quick capture selected text").setIcon("capture").onClick(() => this.openCapture(selection)));
    if (file instanceof import_obsidian4.TFile && file.extension.toLowerCase() === "md") this.addNoteLinkMenuItem(menu, file);
  }
  addFileMenuItems(menu, file) {
    if (file instanceof import_obsidian4.TFile && file.extension.toLowerCase() === "md") this.addNoteLinkMenuItem(menu, file);
  }
  addFilesMenuItems(menu, selected) {
    const paths = /* @__PURE__ */ new Set();
    for (const entry of selected) {
      if (entry instanceof import_obsidian4.TFile && entry.extension.toLowerCase() === "md") paths.add(entry.path);
      else if (entry instanceof import_obsidian4.TFolder) {
        for (const file of this.app.vault.getMarkdownFiles()) if (file.path.startsWith(`${entry.path}/`)) paths.add(file.path);
      }
    }
    const links = [...paths].map((path) => this.app.vault.getAbstractFileByPath(path)).filter((file) => file instanceof import_obsidian4.TFile).map((file) => `[[${file.basename}]]`);
    if (links.length > 1) menu.addItem((item) => item.setTitle(`Kairo: Capture links to ${links.length} selected notes`).setIcon("links-coming-in").onClick(() => this.openCapture(links.join("\n"))));
  }
  addNoteLinkMenuItem(menu, file) {
    menu.addItem((item) => item.setTitle("Kairo: Quick capture link to this note").setIcon("link").onClick(() => this.openCapture(`[[${file.basename}]]`)));
  }
  destinationFor(date = /* @__PURE__ */ new Date()) {
    const relative = this.settings.destinationMode === "daily" ? dailyNotePath(this.settings.dailyFolder, date, this.settings.dailyFormat) : normalizeVaultPath(this.settings.inboxPath);
    return joinVaultPath(this.settings.vaultFolder, relative);
  }
  async capture(text) {
    const trimmed = text.trimEnd();
    if (!trimmed.trim()) throw new Error("Capture is empty.");
    const id = this.makeId();
    if (!await consumeCaptureUse(this, `evt_${id}`)) throw new Error("No capture uses remain. Buy a use pack in Kairo settings.");
    const now = /* @__PURE__ */ new Date();
    const destination = this.destinationFor(now);
    const entry = renderTemplate(this.settings.template, {
      time: formatTimestamp(now, this.settings.timestampFormat),
      source: "Obsidian",
      text: trimmed,
      id
    });
    try {
      await this.appendSafely(destination, entry, id);
      return { state: "saved", id };
    } catch (error) {
      const queued = { id, createdAt: now.getTime(), destination, entry, attempts: 1, lastError: diagnosticSummary(destination, error, id) };
      this.queue.push(queued);
      try {
        await this.persist();
        return { state: "queued", id, diagnostic: queued.lastError };
      } catch (persistError) {
        this.queue = this.queue.filter((item) => item.id !== id);
        queued.lastError = diagnosticSummary(destination, persistError, id);
        return { state: "failed", id, diagnostic: queued.lastError };
      }
    }
  }
  async flushQueue(showNotice) {
    if (this.queueFlushPromise) return this.queueFlushPromise;
    const run = this.flushQueueInternal(showNotice);
    const completion = run.finally(() => {
      if (this.queueFlushPromise === completion) this.queueFlushPromise = void 0;
    });
    this.queueFlushPromise = completion;
    return completion;
  }
  async flushQueueInternal(showNotice) {
    if (!this.queue.length) {
      if (showNotice) new import_obsidian4.Notice("Kairo queue is empty.");
      return;
    }
    const pending = [...this.queue].sort((a, b) => a.createdAt - b.createdAt);
    const pendingIds = new Set(pending.map((item) => item.id));
    const remaining = [];
    let delivered = 0;
    for (const item of pending) {
      try {
        await this.appendSafely(item.destination, item.entry, item.id);
        delivered++;
      } catch (error) {
        remaining.push({ ...item, attempts: item.attempts + 1, lastError: diagnosticSummary(item.destination, error, item.id) });
      }
    }
    const addedDuringFlush = this.queue.filter((item) => !pendingIds.has(item.id));
    this.queue = [...remaining, ...addedDuringFlush].sort((a, b) => a.createdAt - b.createdAt);
    await this.persist();
    if (showNotice) new import_obsidian4.Notice(remaining.length ? `Delivered ${delivered}; ${remaining.length} still queued.` : `Delivered ${delivered} queued capture${delivered === 1 ? "" : "s"}.`);
  }
  async validateDestination() {
    const path = this.destinationFor();
    if (!path) return { ok: false, path, reason: "Choose an inbox file or daily-note folder first." };
    const folder = this.settings.vaultFolder ? this.app.vault.getAbstractFileByPath(normalizeVaultPath(this.settings.vaultFolder)) : null;
    if (this.settings.vaultFolder && !(folder instanceof import_obsidian4.TFolder)) return { ok: false, path, reason: "Vault folder does not exist in the current vault." };
    const file = this.app.vault.getAbstractFileByPath(path);
    if (file && !(file instanceof import_obsidian4.TFile)) return { ok: false, path, reason: "The destination path is a folder, not a Markdown file." };
    if (!file && !this.settings.createMissing) return { ok: false, path, reason: "Destination is missing. Enable 'Create missing destinations' to allow creation." };
    return { ok: true, path };
  }
  async appendSafely(path, entry, marker) {
    const write = this.deliveryChain.catch(() => void 0).then(() => this.appendSafelyUnlocked(path, entry, marker));
    this.deliveryChain = write;
    await write;
  }
  async appendSafelyUnlocked(path, entry, marker) {
    const normalized = (0, import_obsidian4.normalizePath)(path);
    if (!normalized || normalized.includes("../") || normalized === "..") throw new Error("Destination must stay inside the current vault.");
    const existing = this.app.vault.getAbstractFileByPath(normalized);
    if (existing && !(existing instanceof import_obsidian4.TFile)) throw new Error("Destination path is a folder.");
    if (!existing) {
      if (!this.settings.createMissing) throw new Error("Destination file does not exist and creation is disabled.");
      await this.ensureParentFolders(normalized);
      const markedEntry2 = `${entry}${entry.endsWith("\n") ? "" : "\n"}<!-- kairo:${marker} -->
`;
      await this.app.vault.create(normalized, markedEntry2);
      return;
    }
    const file = existing;
    const before = file.stat.mtime;
    const contents = await this.app.vault.read(file);
    if (contents.includes(`<!-- kairo:${marker} -->`)) return;
    const current = file.stat.mtime;
    if (current !== before) throw new DestinationChangedError();
    const markedEntry = `${entry}${entry.endsWith("\n") ? "" : "\n"}<!-- kairo:${marker} -->
`;
    await this.app.vault.modify(file, appendText(contents, markedEntry));
  }
  async ensureParentFolders(path) {
    const parts = path.split("/");
    parts.pop();
    let current = "";
    for (const part of parts) {
      current = current ? `${current}/${part}` : part;
      const existing = this.app.vault.getAbstractFileByPath(current);
      if (existing && !(existing instanceof import_obsidian4.TFolder)) throw new Error(`Cannot create destination folder: ${current} is a file.`);
      if (!existing) await this.app.vault.createFolder(current);
    }
  }
  copyDiagnostic(summary) {
    var _a;
    const write = (_a = navigator.clipboard) == null ? void 0 : _a.writeText(summary);
    if (write) void write.then(() => new import_obsidian4.Notice("Diagnostic copied. Captured text was not included."));
    else new import_obsidian4.Notice("Clipboard access is unavailable. The diagnostic is visible in the queue.");
  }
  makeId() {
    const bytes = new Uint8Array(8);
    crypto.getRandomValues(bytes);
    return `kairo-${Date.now().toString(36)}-${Array.from(bytes, (value) => value.toString(16).padStart(2, "0")).join("")}`;
  }
  registerGlobalShortcut() {
    this.unregisterGlobalShortcut();
    const electron = this.electron();
    if (!(electron == null ? void 0 : electron.globalShortcut)) return;
    try {
      if (electron.globalShortcut.register(this.settings.shortcut, () => this.openCapture())) this.globalShortcut = this.settings.shortcut;
    } catch (e) {
    }
  }
  unregisterGlobalShortcut() {
    var _a, _b;
    if (!this.globalShortcut) return;
    try {
      (_b = (_a = this.electron()) == null ? void 0 : _a.globalShortcut) == null ? void 0 : _b.unregister(this.globalShortcut);
    } catch (e) {
    }
    this.globalShortcut = void 0;
  }
  applyLaunchAtLogin() {
    var _a, _b, _c;
    try {
      (_c = (_b = (_a = this.electron()) == null ? void 0 : _a.app) == null ? void 0 : _b.setLoginItemSettings) == null ? void 0 : _c.call(_b, { openAtLogin: this.settings.launchAtLogin });
    } catch (e) {
    }
  }
  refreshShortcut() {
    this.registerGlobalShortcut();
  }
  pollAfterCheckout(checkoutId) {
    if (this.checkoutPollTimer !== void 0) window.clearInterval(this.checkoutPollTimer);
    let attempts = 0;
    this.checkoutPollTimer = window.setInterval(() => {
      attempts += 1;
      void (async () => {
        const settled = checkoutId ? await pollAuthenticatedCheckout(this, checkoutId).catch(() => false) : false;
        if (settled) await syncPurchasedUses(this);
        else if (!checkoutId) await syncPurchasedUses(this);
        if ((settled || attempts >= 6) && this.checkoutPollTimer !== void 0) {
          window.clearInterval(this.checkoutPollTimer);
          this.checkoutPollTimer = void 0;
        }
      })();
    }, 15e3);
  }
  electron() {
    const requireFn = window.require;
    if (!requireFn) return void 0;
    try {
      return requireFn("electron");
    } catch (e) {
      return void 0;
    }
  }
};
var CaptureModal = class extends import_obsidian4.Modal {
  constructor(app, plugin, initialText = "") {
    super(app);
    this.plugin = plugin;
    this.initialText = initialText;
  }
  onOpen() {
    this.modalEl.addClass("kairo-capture-modal");
    this.titleEl.setText("Quick capture");
    this.contentEl.empty();
    this.contentEl.createEl("p", { text: "Capture locally; Kairo will deliver it to your configured destination." });
    this.textarea = this.contentEl.createEl("textarea", { attr: { ariaLabel: "Capture text", rows: "7", placeholder: "What do you want to remember?" } });
    this.textarea.value = this.initialText;
    this.status = this.contentEl.createDiv({ cls: "kairo-status", attr: { role: "status", "aria-live": "polite" } });
    this.status.setText("Ready");
    const actions = this.contentEl.createDiv({ cls: "kairo-actions" });
    const save = actions.createEl("button", { text: "Save" });
    const saveClose = actions.createEl("button", { text: "Save and close", cls: "mod-cta" });
    const cancel = actions.createEl("button", { text: "Cancel" });
    save.addEventListener("click", () => void this.submit(false));
    saveClose.addEventListener("click", () => void this.submit(true));
    cancel.addEventListener("click", () => this.close());
    this.textarea.addEventListener("keydown", (event) => {
      if (event.key === "Escape") {
        event.preventDefault();
        this.close();
      }
      if ((event.ctrlKey || event.metaKey) && event.key === "Enter") {
        event.preventDefault();
        void this.submit(this.plugin.settings.closeAfterSaving);
      }
    });
    window.setTimeout(() => this.textarea.focus(), 20);
  }
  async submit(closeAfter) {
    if (!this.textarea.value.trim()) {
      this.status.setText("Enter some text first.");
      return;
    }
    this.status.setText("Saving\u2026");
    try {
      const result = await this.plugin.capture(this.textarea.value);
      if (result.state === "saved") {
        this.status.setText("Saved");
        new import_obsidian4.Notice("Capture saved.");
        if (closeAfter || this.plugin.settings.closeAfterSaving) this.close();
      } else if (result.state === "queued") {
        this.diagnostic = result.diagnostic;
        this.status.setText("Queued \u2014 destination unavailable. Your text is safe locally.");
        this.addDiagnosticAction();
        if (closeAfter) this.close();
      } else {
        this.diagnostic = result.diagnostic;
        this.status.setText("Failed \u2014 the capture could not be persisted. Keep this window open and retry.");
        this.addDiagnosticAction();
      }
    } catch (error) {
      this.status.setText(error instanceof Error ? error.message : "Could not save capture.");
    }
  }
  addDiagnosticAction() {
    if (!this.diagnostic) return;
    const copy = this.contentEl.createEl("button", { text: "Copy diagnostic" });
    copy.addEventListener("click", () => {
      var _a;
      return this.plugin.copyDiagnostic((_a = this.diagnostic) != null ? _a : "");
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var QueueModal = class extends import_obsidian4.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    this.titleEl.setText("Queued captures");
    this.contentEl.empty();
    if (!this.plugin.queue.length) {
      this.contentEl.createEl("p", { text: "Nothing is waiting for delivery." });
      return;
    }
    this.contentEl.createEl("p", { text: `${this.plugin.queue.length} capture${this.plugin.queue.length === 1 ? "" : "s"} waiting. Captured text stays in this vault's plugin data until delivery.` });
    const list = this.contentEl.createEl("ul", { cls: "kairo-queue-list" });
    for (const item of [...this.plugin.queue].sort((a, b) => a.createdAt - b.createdAt)) {
      const row = list.createEl("li");
      row.createEl("strong", { text: new Date(item.createdAt).toLocaleString() });
      row.createEl("span", { text: ` \xB7 ${item.destination} \xB7 ${item.attempts} attempt${item.attempts === 1 ? "" : "s"}` });
      if (item.lastError) {
        row.createEl("p", { text: item.lastError, cls: "kairo-queue-error" });
        const copy = row.createEl("button", { text: "Copy diagnostic" });
        copy.addEventListener("click", () => {
          var _a;
          return this.plugin.copyDiagnostic((_a = item.lastError) != null ? _a : "");
        });
      }
    }
    const retry = this.contentEl.createEl("button", { text: "Retry all", cls: "mod-cta" });
    retry.addEventListener("click", () => {
      void this.plugin.flushQueue(true).then(() => this.close());
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var KairoSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    this.plugin.support.addDiagnosticsSetting(containerEl);
    containerEl.createEl("p", { text: "Local-first capture. The optional Electron shortcut is active while Obsidian is running; the Obsidian command hotkey is always available as a fallback." });
    new import_obsidian4.Setting(containerEl).setName("Billing & usage").setHeading();
    containerEl.createEl("p", { text: "Each capture uses 1 credit. Billing accounts get 3 free captures per UTC day across all linked installations. Paid packs are one-time purchases: $1 for 100 uses or $10 for 1,000 uses." });
    this.usageSummaryEl = containerEl.createEl("p", { cls: "kairo-usage-summary", attr: { role: "status", "aria-live": "polite" } });
    this.renderUsageSummary();
    addBillingAccountSettings(containerEl, {
      state: this.plugin.settings,
      appId: "kairo-quick-capture",
      installationId: this.plugin.settings.constanceDeviceId,
      appVersion: this.plugin.manifest.version,
      persist: () => this.plugin.persist(),
      syncBalance: () => syncPurchasedUses(this.plugin),
      refresh: () => this.display()
    });
    new import_obsidian4.Setting(containerEl).setName("Buy capture uses").setDesc("Opens TutivSoft Constance checkout in your browser. Purchases are one-time and linked to this installation.").addButton((button) => button.setButtonText("Buy $1 \xB7 100 uses").onClick(() => openBuyCheckout(this.plugin, "usd_001"))).addButton((button) => button.setButtonText("Buy $10 \xB7 1,000 uses").setCta().onClick(() => openBuyCheckout(this.plugin, "usd_010")));
    new import_obsidian4.Setting(containerEl).setName("Refresh purchased balance").setDesc("Pull the latest purchased-use balance from Constance.").addButton((button) => button.setButtonText("Refresh").onClick(async () => {
      button.setDisabled(true);
      await syncPurchasedUses(this.plugin);
      this.renderUsageSummary();
      button.setDisabled(false);
    }));
    new import_obsidian4.Setting(containerEl).setName("Global shortcut").setDesc("Desktop accelerator, for example Ctrl+Shift+Space. Restart the shortcut after editing.").addText((text) => text.setValue(this.plugin.settings.shortcut).onChange(async (value) => {
      this.plugin.settings.shortcut = value.trim() || DEFAULT_SETTINGS.shortcut;
      this.plugin.refreshShortcut();
      await this.plugin.persist();
    }));
    new import_obsidian4.Setting(containerEl).setName("Vault folder").setDesc("Optional folder inside the current vault. Kairo never writes outside the current vault.").addText((text) => text.setPlaceholder("Leave blank for vault root").setValue(this.plugin.settings.vaultFolder).onChange(async (value) => {
      this.plugin.settings.vaultFolder = normalizeVaultPath(value);
      await this.plugin.persist();
    }));
    new import_obsidian4.Setting(containerEl).setName("Destination mode").setDesc("Choose one inbox file or a dated daily-note folder.").addDropdown((dropdown) => dropdown.addOptions({ inbox: "Inbox file", daily: "Daily note" }).setValue(this.plugin.settings.destinationMode).onChange(async (value) => {
      this.plugin.settings.destinationMode = value;
      await this.plugin.persist();
      this.display();
    }));
    new import_obsidian4.Setting(containerEl).setName("Inbox file").setDesc("Relative Markdown path used in inbox mode.").addText((text) => text.setValue(this.plugin.settings.inboxPath).onChange(async (value) => {
      this.plugin.settings.inboxPath = normalizeVaultPath(value) || DEFAULT_SETTINGS.inboxPath;
      await this.plugin.persist();
    }));
    new import_obsidian4.Setting(containerEl).setName("Daily-note folder").setDesc("Relative folder used in daily-note mode.").addText((text) => text.setValue(this.plugin.settings.dailyFolder).onChange(async (value) => {
      this.plugin.settings.dailyFolder = normalizeVaultPath(value);
      await this.plugin.persist();
    }));
    new import_obsidian4.Setting(containerEl).setName("Daily-note format").setDesc("Filename format: YYYY, MM, DD, HH, mm, ss.").addText((text) => text.setValue(this.plugin.settings.dailyFormat).onChange(async (value) => {
      this.plugin.settings.dailyFormat = value || DEFAULT_SETTINGS.dailyFormat;
      await this.plugin.persist();
    }));
    new import_obsidian4.Setting(containerEl).setName("Timestamp format").setDesc("Template time format: YYYY, MM, DD, HH, mm, ss.").addText((text) => text.setValue(this.plugin.settings.timestampFormat).onChange(async (value) => {
      this.plugin.settings.timestampFormat = value || DEFAULT_SETTINGS.timestampFormat;
      await this.plugin.persist();
    }));
    new import_obsidian4.Setting(containerEl).setName("Capture template").setDesc("Use {{time}}, {{source}}, {{text}}, and {{id}}. The id marker prevents duplicate retries.").addTextArea((text) => text.setValue(this.plugin.settings.template).onChange(async (value) => {
      this.plugin.settings.template = value || DEFAULT_TEMPLATE;
      await this.plugin.persist();
    }));
    new import_obsidian4.Setting(containerEl).setName("Create missing destinations").setDesc("When enabled, Kairo creates the configured Markdown file on the first capture.").addToggle((toggle) => toggle.setValue(this.plugin.settings.createMissing).onChange(async (value) => {
      this.plugin.settings.createMissing = value;
      await this.plugin.persist();
    }));
    new import_obsidian4.Setting(containerEl).setName("Close after saving").setDesc("Close the scratchpad after a successful save.").addToggle((toggle) => toggle.setValue(this.plugin.settings.closeAfterSaving).onChange(async (value) => {
      this.plugin.settings.closeAfterSaving = value;
      await this.plugin.persist();
    }));
    new import_obsidian4.Setting(containerEl).setName("Launch at login").setDesc("Optional desktop convenience. Disabled by default and handled locally by Electron when supported.").addToggle((toggle) => toggle.setValue(this.plugin.settings.launchAtLogin).onChange(async (value) => {
      this.plugin.settings.launchAtLogin = value;
      this.plugin.applyLaunchAtLogin();
      await this.plugin.persist();
    }));
    new import_obsidian4.Setting(containerEl).setName("Queue").setDesc(`${this.plugin.queue.length} capture${this.plugin.queue.length === 1 ? "" : "s"} waiting for delivery.`).addButton((button) => button.setButtonText("Show queue").onClick(() => new QueueModal(this.app, this.plugin).open())).addButton((button) => button.setButtonText("Flush now").onClick(() => void this.plugin.flushQueue(true)));
    new import_obsidian4.Setting(containerEl).setName("Validate destination").setDesc("Check the configured destination without writing a test note.").addButton((button) => button.setButtonText("Validate").onClick(async () => {
      var _a;
      const result = await this.plugin.validateDestination();
      new import_obsidian4.Notice(result.ok ? `Kairo: destination ready at ${result.path}.` : `Kairo: ${(_a = result.reason) != null ? _a : "destination is not ready"}`);
    }));
    void syncPurchasedUses(this.plugin).then(() => this.renderUsageSummary());
  }
  renderUsageSummary() {
    if (!this.usageSummaryEl) return;
    normalizeBillingSettings(this.plugin.settings);
    const total = this.plugin.settings.freeUsesRemaining + this.plugin.settings.purchasedUses;
    const account = this.plugin.settings.billingAccountLinked ? "account linked" : "sign in required";
    this.usageSummaryEl.setText(`Uses remaining: ${total.toLocaleString()} (${this.plugin.settings.freeUsesRemaining} free today + ${this.plugin.settings.purchasedUses.toLocaleString()} purchased; ${account})`);
  }
};
